# This script compiles Multivac program.
# Author: Vivien Mallet.

from glob import glob

# SCons environment.
env = Environment()


###########
# OPTIONS #
###########


# Compilation options.
if ARGUMENTS.get("debug", "0") == "0":
    env.Replace(CCFLAGS = "-O2")
elif ARGUMENTS["debug"] == "1":
    env.Replace(CCFLAGS = "-g -Wall -ansi -pedantic")
    env.Replace(LINKFLAGS = " -g")
elif ARGUMENTS["debug"] == "2":
    env.Replace(CCFLAGS = "-O2 -g -Wall -ansi -pedantic")
    env.Replace(LINKFLAGS = " -g")
else:
    env.Replace(CCFLAGS = "")

# Compilation lines.
if ARGUMENTS.get("line", "no") == "no":
    env.Replace(CXXCOMSTR = "[C++] $SOURCE")
    env.Replace(LINKCOMSTR = "[Linking] $TARGET")


##########################
# ENVIRONMENT DEFINITION #
##########################


cpp_path = "includes"

# Paths.
env.Replace(CPPPATH = Split(cpp_path))


############
# PROGRAMS #
############


program_list = glob("*.cpp")

for program in program_list:
    env.Program(program[:-4], program)
